use_frameworks!

platform :ios, '9.0'

target 'HXViewHUD_Example' do
  pod 'HXViewHUD', :path => '../'

#  pod 'WechatOpenSDK', :path => './'

#  pod 'WechatOpenSDK', :git => 'https://github.com/TheLittleBoy/CocoaPods.git'
  
#  pod 'WechatOpenSDK', :podspec => './WechatOpenSDK.podspec'
  
#  pod 'WechatOpenSDK', :podspec => './'

#  pod 'WechatOpenSDK'
  
  
  target 'HXViewHUD_Tests' do
    inherit! :search_paths

    
  end
end
